image: tuxtor/graalvm-ce-native-maven:20.1.0-java11

pipelines:
  branches:
    develop:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean package
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean verify
          artifacts:
            - target/**
      - step:
          name: Deploy artifacts using SCP to PROD
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: externossh
                SERVER: demo.nabenik.com
                REMOTE_PATH: '/var/www/clients/client4/web4/web/yum/'
                LOCAL_PATH: 'target/*.rpm'
