image: tuxtor/graalvm-ce-native-maven:20.1.0-java11

pipelines:
  branches:
    develop:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean package
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean verify
          artifacts:
            - target/**
      - step:
          name: Deploy artifacts using SCP to PROD
          deployment: production
          script:
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "target/*.rpm"
