image: tuxtor/graalvm-ce-native-maven:20.1.0-java11

pipelines:
  branches:
    develop:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean package
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean verify
